import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

<%_ if(oauth2) {_%>
  import SessionProvider from "./providers/SessionProvider";
  import {getServerSession} from 'next-auth';
<%_ } _%>


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "<%= baseName %>",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  <%_ if(oauth2) {_%>
    const userSession = await getServerSession();
  <%_ } _%>
  return (
    <html lang="en">
      <body className={inter.className}>
      <%_ if(oauth2) {_%>
        <SessionProvider session={userSession} >
        {children}
        </SessionProvider>
      <%_ } else { _%>
          {children}
        <%_ } _%>
      </body>
    </html>
  );
}
