package main

import (
	"github.com/gorilla/mux"
	"log"
	"os"
	"net/http"
	"<%= packageName %>/db"
	"<%= packageName %>/controllers"
	_ "<%= packageName %>/docs"
	"<%= packageName %>/customlogger"
    "github.com/joho/godotenv"
	"github.com/google/uuid"
	// _ "swaggo-events-api/docs" // docs is generated by Swag CLI, you have to import it.
	// httpSwagger "github.com/swaggo/http-swagger"

)

func goDotEnvVariable(key string) string {
	err := godotenv.Load(".env")
	if err != nil {
	  log.Fatalf("Error loading .env file")
	}
	return os.Getenv(key)
  }
var configurations RegistrationVariables

func init() {
	service_registry :=goDotEnvVariable("SERVICE_REGISTRY")
	service_registry_url :=goDotEnvVariable("SERVICE_REGISTRY_URL")
	InstanceId := "<%= baseName %>:"+uuid.New().String()
	configurations = RegistrationVariables{service_registry,service_registry_url,InstanceId}
}

// @title Events API
// @version 1.0
// @description This is a sample service for managing events
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:7090
// @BasePath /
func main() {
	// props, _ := ft.ReadPropertiesFile("config.properties")
	port := goDotEnvVariable("SERVICE_PORT")
	config.DbConnect()
	customlogger.Printfun("info","Starting")    
	router := mux.NewRouter().StrictSlash(true)
	router.Use(commonMiddleware)
	registerRoutes(router)
	go ManageDiscovery(configurations)
	customlogger.Printfun("info","Service Registered with Eureka")    
	portsno  :=":"+port
	log.Fatal(http.ListenAndServe(portsno, router))
}

func registerRoutes (router *mux.Router){
	registerControllerRoutes(controllers.EventController{}, router)
}

func registerControllerRoutes(controller controllers.Controller, router *mux.Router) {
	controller.RegisterRoutes(router)
}

func commonMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Add("Content-Type", "application/json")
		next.ServeHTTP(w, r)
	})
}
