// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package db

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// XXX_NoUnkeyedLiteral struct{} `json:"-"`
	// XXX_unrecognized     []byte   `json:"-"`
	// XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type NotesRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// XXX_NoUnkeyedLiteral struct{} `json:"-"`
	// XXX_unrecognized     []byte   `json:"-"`
	// XXX_sizecache        int32    `json:"-"`
}

func (m *NotesRequest) Reset()         { *m = NotesRequest{} }
func (m *NotesRequest) String() string { return proto.CompactTextString(m) }
func (*NotesRequest) ProtoMessage()    {}
func (*NotesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *NotesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotesRequest.Unmarshal(m, b)
}
func (m *NotesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotesRequest.Marshal(b, m, deterministic)
}
func (m *NotesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotesRequest.Merge(m, src)
}
func (m *NotesRequest) XXX_Size() int {
	return xxx_messageInfo_NotesRequest.Size(m)
}
func (m *NotesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotesRequest proto.InternalMessageInfo

func (m *NotesRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *NotesRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type NotesResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// XXX_NoUnkeyedLiteral struct{} `json:"-"`
	// XXX_unrecognized     []byte   `json:"-"`
	// XXX_sizecache        int32    `json:"-"`
}

func (m *NotesResponse) Reset()         { *m = NotesResponse{} }
func (m *NotesResponse) String() string { return proto.CompactTextString(m) }
func (*NotesResponse) ProtoMessage()    {}
func (*NotesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *NotesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotesResponse.Unmarshal(m, b)
}
func (m *NotesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotesResponse.Marshal(b, m, deterministic)
}
func (m *NotesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotesResponse.Merge(m, src)
}
func (m *NotesResponse) XXX_Size() int {
	return xxx_messageInfo_NotesResponse.Size(m)
}
func (m *NotesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotesResponse proto.InternalMessageInfo

func (m *NotesResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotesResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *NotesResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MyMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// XXX_NoUnkeyedLiteral struct{} `json:"-"`
	// XXX_unrecognized     []byte   `json:"-"`
	// XXX_sizecache        int32    `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{3}
}

func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

func (m *MyMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MyMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "db.Event")
	proto.RegisterType((*NotesRequest)(nil), "db.NotesRequest")
	proto.RegisterType((*NotesResponse)(nil), "db.NotesResponse")
	proto.RegisterType((*MyMessage)(nil), "db.MyMessage")
}

func init() {
	proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374)
}

var fileDescriptor_8817812184a13374 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x49, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4a, 0x49, 0x52, 0xf2, 0xe7, 0x62, 0x75, 0x2d, 0x4b, 0xcd,
	0x2b, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca,
	0x4c, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0x2c, 0xc9, 0x49, 0x95, 0x60, 0x02, 0x0b, 0x41, 0x38,
	0x42, 0x0a, 0x5c, 0xdc, 0x29, 0xa9, 0xc5, 0xc9, 0x45, 0x99, 0x05, 0x25, 0x99, 0xf9, 0x79, 0x12,
	0xcc, 0x60, 0x39, 0x64, 0x21, 0x25, 0x2f, 0x2e, 0x1e, 0xbf, 0xfc, 0x92, 0xd4, 0xe2, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x09, 0x2e, 0xf6, 0xe2, 0xd2, 0xa4, 0xac, 0xd4, 0xe4, 0x12,
	0xa8, 0xe1, 0x30, 0x2e, 0xba, 0x59, 0x4c, 0x98, 0x66, 0x45, 0x73, 0xf1, 0x42, 0xcd, 0x2a, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0x70, 0x24, 0x92, 0xe1, 0x4c, 0x78, 0x0d, 0xc7, 0xe2, 0x50, 0x7d,
	0x2e, 0x4e, 0xdf, 0x4a, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0x74, 0x4c, 0x83, 0x85, 0xb8, 0x58, 0x52,
	0x12, 0x4b, 0x12, 0xa1, 0xa6, 0x82, 0xd9, 0x4e, 0x3c, 0x51, 0x5c, 0x7a, 0xfa, 0xe0, 0x90, 0xb3,
	0x4e, 0x49, 0x4a, 0x62, 0x03, 0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x96, 0x53, 0x14,
	0x4b, 0x4f, 0x01, 0x00, 0x00,
}
